---

phonebook-app-app_source_repo: "https://github.com/diranetafen/crud-application-using-flask-and-mysql.git"
phonebook-app-app_source_branch: "master"

phonebook-app-app_docker_image_tag: "v1"

home: "/home/centos"

#secret data vaulted
gitlab_private_key: "{{ vault_gitlab_private_key }}"
docker_hub_login: "{{ vault_docker_hub_login }}"
docker_hub_email: "{{ vault_docker_hub_email }}"
docker_hub_password: "{{ vault_docker_hub_password }}"
