---
- name: Ensure application is deployed
  hosts: prod
  become: true
  tasks:
    - block:
        - name: Check that you can connect to webpage
          uri:
            url: http://3.83.8.188
          retries: 8
          delay: 15
