# Install a role for pip
- src: geerlingguy.pip

# Install a role for docker
- src: geerlingguy.docker

# Install a role for gitlab/gitlab-runner
- src: https://github.com/HP41/ansible-docker-gitlab.git

