---

# This playbook is used to deploy student-list application based on Docker

# build and push builded images

- name: Log into DockerHub
  docker_login:
    username: "{{ docker_hub_login }}"
    email: "{{ docker_hub_email }}"
    password: "{{ docker_hub_password }}"
  tags:
    - build
- name: create project directory
  file:
    path: "{{ home }}/phonebook"
    state: directory
  tags:
    - build
    - deploy

- name: copy devops private key file
  copy:
    content: '{{ gitlab_private_key }}'
    dest: "{{ home }}/.ssh/id_rsa"
    owner: centos
  tags:
    - build
    - deploy

- name: retrieve bulletin app code source
  git:
    repo: https://github.com/diranetafen/crud-application-using-flask-and-mysql.git 
    dest: "{{ home }}/phonebook/"
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "{{ home }}/.ssh/id_rsa"
    version: master
  tags:
    - build

- name: Build api image
  docker_image:
    path: "{{ home }}/phonebook/"
    dockerfile: Dockerfile-mysql
    name: "{{ docker_hub_login }}/phonebook-mysql"
    push: yes
    tag: v1
  tags:
    - build

- name: Build api image and push it to Docker Hub
  docker_image:
    path: "{{ home }}/phonebook-app/Dockerfile-app"
    name: "{{ docker_hub_login }}/phonebook-app"
    push: yes
    tag: v1
  tags:
    - build

# docker network 

- name: crete docker network to interconnect containers
  docker_network:
    name: phonebook-network

# deploy api

- name: Deploy api
  docker_container:
    name: phonebook-db 
    hostname: phonebook-db
    image: vumay/phonebook-mysql:v1
    state: started
    restart_policy: always
    networks:
      - name: phonebook-network
    ports:
      - "4000:5000"

# deploy frontend

- name: Deploy frontend
  docker_container:
    name: phonebook-app
    image: phonebook-app:v1
    state: started
    restart_policy: always
    networks:
      - name: phonebook-network
    ports:
      - "80:8181"
